### ISSUE TITLE
Deploy script fails if zip file is named differently

### ISSUE THREAD

**Issue by jzeltman** [adobe/aem-site-template-basic#22]
Steps to reproduce:
1. Clone/fork repo
2. Run build script
3. Zip file is created with aem-site-template-basic.zip
4. Run deploy script
5. Build script fails because it is looking for site-template.zip which doesn't exist

**Comment by bartoszglow** [comment]
Hi @jzeltman,

could you please provide your aem-site-template-basic version and version of aem-site-template-builder package (available in ./package.json)?

**Comment by jzeltman** [comment]
@bartoszglow Which was directly forked from 4.0.1
Here's the repo: https://github.com/jzeltman/aem-site-template-test-1

**Comment by bartoszglow** [comment]
Fix provided in version [4.0.2](https://github.com/adobe/aem-site-template-basic/releases/tag/v4.0.2)
