### ISSUE TITLE
Changes in code are not reflected on AEM instance

### ISSUE THREAD

**Issue by thisisui** [adobe/aem-site-template-basic#27]
### Expected Behaviour
Changes in code are reflected on instance.

### Actual Behaviour
Changes in code are not deployed on instance after all steps from Wiki.

#### Steps to Reproduce
I followed all steps in wiki and also got a successful build on github actions.
You can check my repo here: https://github.com/thisisui/simple-theme/actions

Unfortunately on an instance I do not see any changes. Even when I download the theme once again from AEM I am still getting unchanged files.

In wiki it is written that `Update theme config` will be run after `Build and deploy` task but I cannot see in the logs any information that `Update theme config` has been started. Is there any way to debug this as I have no idea how to fix it.

Cheers
Igor

**Comment by bpauli** [comment]
@Hi @thisisui, what version of the Basic Site Template did you use when you followed the steps form the wiki? Please make sure to use the latest pre-release which is available at https://github.com/adobe/aem-site-template-basic/releases

**Comment by thisisui** [comment]
Thank @bpauli 

I used the latest but what I see after discussion with my colleagues it's about setting proper permission when you create a Token in Github. 

Now in wiki in C.1 we can see `check all of "repo" and "workflow"` and this is solving the issue of not triggering Update theme config. I will close this issues as this update in wiki now fixes the issue.
