### ISSUE TITLE
EPERM Error on Windows OS

### ISSUE THREAD

**Issue by toniadobe** [adobe/aem-site-template-basic#34]
When saving CSS code changes, browser sync does not sync to reflect the updated code after refreshing the browser and receives an EPERM error in the Command console.  This happens on my Adobe issue Windows machine with Anti Virus Software running.  

### Expected Behaviour
Refreshing the browser should reflect css changes.

### Actual Behaviour
EPERM error displays in the command console.  

### Reproduce Scenario (including but not limited to)
Update CSS in _variables.scss, save the file and refresh the browser, EPERM error occurs 

#### Steps to Reproduce
navigate to the the theme-sources folder in a command window
run:  npm live run
Update the background hex color in _variables.scss as instructed in the tutorial and save the file
in a web browser navigate to: http://localhost:7000/content/basic/en.html and refresh the page
View command window and an EPERM operation not permitted, lstat

#### Platform and Version
Windows 10 -OS
Carbon Black  - Virsus scan software running (unable to turn it off)

#### Logs taken while reproducing problem

![image](https://user-images.githubusercontent.com/44175606/110680192-4826f900-81a6-11eb-9f2a-37370929fe04.png)

**Comment by bartoszglow** [comment]
fixed in `5.1.2` release
