### ISSUE TITLE
Experience Fragment Styling

### ISSUE THREAD

**Issue by williarrmo** [adobe/aem-site-template-basic#54]
### Expected Behaviour
Editing the Header XF within the basic site template, that the XF displays as per the new pages that are created

### Actual Behaviour
XF fragment dissplays in an un-styled format, meaning i cant edit this branding

### Reproduce Scenario (including but not limited to)
Create new site using basic site template 5.1.2
Edit the header XF

#### Steps to Reproduce
Create new site using basic site template 5.1.2
Edit the header XF

#### Platform and Version
AEMaaCS

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
N/A
![Screen Shot 2021-08-18 at 5 32 51 pm](https://user-images.githubusercontent.com/37498810/129856874-b08a1de2-70a9-46ab-926f-f4ab82cfd0d5.png)

**Comment by vladbailescu** [comment]
There seem to be two different issues that are causing this:

1. The header css assumes `.experiencefragment.header` classes are present on the header wrapper (https://github.com/adobe/aem-site-template-basic/blob/e2e159f3fea918ca2d691f1731c75486ad0a241d/theme/src/components/experiencefragment/_experiencefragment_header.scss#L3). That's not happening when editing the XF.
2. The XF page policy is missing the base clientlibs from the Core Components:
